copy C:\platform\fca4j-project\fca4j-app-light\target\fca4j-app-light-0.5.1-jar-with-dependencies.jar C:\platform\fca4j-ui\src\main\resources\fr\lirmm\fca4j\ui\bin\fca4j.jar
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-parent\0.5.1\fca4j-parent-0.5.1.pom C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-iset\0.5.1\fca4j-iset-0.5.1.pom C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-iset\0.5.1\fca4j-iset-0.5.1.jar C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-io\0.5.1\fca4j-io-0.5.1.pom C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-io\0.5.1\fca4j-io-0.5.1.jar C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-core\0.5.1\fca4j-core-0.5.1.pom C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-core\0.5.1\fca4j-core-0.5.1.jar C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-core-natif\0.5.1\fca4j-core-natif-0.5.1.pom C:\platform\fca4j-ui\lib\
copy C:\Users\gutierre\.m2\repository\fr\lirmm\fca4j\fca4j-core-natif\0.5.1\fca4j-core-natif-0.5.1.jar C:\platform\fca4j-ui\lib\
