app.version=${project.version}
app.name=${project.name}
app.url=${project.url}
app.inception=${project.inceptionYear}
app.license=BSD-3-Clause
app.scm=${project.scm.url}
app.org.name=${project.organization.name}
app.dev.1.name=${app.dev.1.name}
app.dev.1.org=${app.dev.1.org}
app.dev.2.name=${app.dev.2.name}
app.dev.2.org=${app.dev.2.org}
app.dev.3.name=${app.dev.3.name}
app.dev.3.org=${app.dev.3.org}
app.org.name=${app.org.name}
app.org.url=${app.org.url}